// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using ui_design_12_21_2017.Data;

namespace ui_design_12_21_2017.Migrations
{
    [DbContext(typeof(InvoicesContext))]
    partial class InvoicesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ui_design_12_21_2017.Models.ContractGroup", b =>
                {
                    b.Property<string>("Name");

                    b.HasKey("Name");

                    b.ToTable("ContractGroups");
                });

            modelBuilder.Entity("ui_design_12_21_2017.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ui_design_12_21_2017.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceNumber");

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("Balance");

                    b.Property<string>("ContractGroupName")
                        .IsRequired();

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("DueDate");

                    b.Property<bool>("IsApproved");

                    b.Property<int>("IsoId");

                    b.Property<string>("LdcAccountNumber");

                    b.Property<int>("StatusId");

                    b.HasKey("InvoiceNumber");

                    b.HasIndex("ContractGroupName");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsoId");

                    b.HasIndex("LdcAccountNumber");

                    b.HasIndex("StatusId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ui_design_12_21_2017.Models.Iso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Isos");
                });

            modelBuilder.Entity("ui_design_12_21_2017.Models.LdcAccount", b =>
                {
                    b.Property<string>("LdcAccountNumber");

                    b.HasKey("LdcAccountNumber");

                    b.ToTable("LdcAccounts");
                });

            modelBuilder.Entity("ui_design_12_21_2017.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ui_design_12_21_2017.Models.Invoice", b =>
                {
                    b.HasOne("ui_design_12_21_2017.Models.ContractGroup", "ContractGroup")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractGroupName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ui_design_12_21_2017.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ui_design_12_21_2017.Models.Iso", "Iso")
                        .WithMany("Invoices")
                        .HasForeignKey("IsoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ui_design_12_21_2017.Models.LdcAccount", "LdcAccount")
                        .WithMany("Invoices")
                        .HasForeignKey("LdcAccountNumber");

                    b.HasOne("ui_design_12_21_2017.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
